### ISSUE TITLE
Blog – TypeTerms.com

### ISSUE THREAD

**Issue by signalwerk** [signalwerk/walz.alexanderboenninger#10]
Hast du @exeldoc noch die Liste mit möglicher domain-namen für TypeTerms.com, die du dir notiert hattest, während wir gesprochen hatten?

**Comment by exeldoc** [comment]
URLs:
www.terms.cc
www.printers-terms.design
www.terms.design
www.terms.press
www.ter.ms
www.printers-terms.ch
www.designers-terms.ch
www.typo-terms.ch
www.letter-terms.ch
book-terms.ch
www.typography-terms.ch
www.tranlation.design
www.type-terms.ch
www.TypeTerms.com
TypeTerms.com

**Comment by signalwerk** [comment]
danke dir. hier der post (bisschen textlastig...) https://signalwerk.github.io/walz.alexanderboenninger/posts/typeterms-naming/
